// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaflnT_Rhq-JBnjCti3cLNUIykfwhozds',
    appId: '1:150068478515:web:0d6739fb983299d0aa9946',
    messagingSenderId: '150068478515',
    projectId: 'thanki22',
    authDomain: 'thanki22.firebaseapp.com',
    storageBucket: 'thanki22.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACnPeV3v9u_zc1aD_W3-lN8gxRAoOfVLo',
    appId: '1:150068478515:android:b58c79cf986e32e7aa9946',
    messagingSenderId: '150068478515',
    projectId: 'thanki22',
    storageBucket: 'thanki22.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs82pm_DOuXO_bgawe3CmbEmJfH68c1HQ',
    appId: '1:150068478515:ios:8714a2508d9c8ad4aa9946',
    messagingSenderId: '150068478515',
    projectId: 'thanki22',
    storageBucket: 'thanki22.appspot.com',
    iosBundleId: 'com.example.thankiApp',
  );
}
